# Generated by Django 5.2.7 on 2025-10-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Universidades', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrefacultad', models.CharField(max_length=100)),
                ('cod_facultad', models.CharField(max_length=20)),
                ('ubicación', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Universidades/universidad/static/facultad_fotos/')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
    ]
