# Generated by Django 5.2.7 on 2025-10-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidades', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecarrera', models.CharField(max_length=100)),
                ('cod_facultad', models.CharField(max_length=20)),
                ('duracion_años', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Carreras', to='Universidades.faculty')),
            ],
        ),
    ]
